backend:
  name: git-gateway
  branch: main # Asegúrate de que esté apuntando a la rama correcta de tu repositorio
media_folder: "assets/images" # Aquí se guardarán las imágenes cargadas
public_folder: "/assets/images" # Ruta pública de las imágenes
collections:
  - name: "products" # Nombre de la colección
    label: "Products"
    folder: "products" # La carpeta donde se guardarán los productos
    create: true
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
